exports.configureParams = templateParams => {
    console.log('config')
    return {
        // unsplashId: 'OeC1wIsKNpk',
        imageUrl: "https://images.unsplash.com/photo-1557958114-3d2440207108?w=1950&q=80",
        ...templateParams,
        watermark: 'Generated by ang-e',
    }
};