// imageUrl: "https://images.unsplash.com/photo-1557958114-3d2440207108?w=1950&q=80",

exports.configureParams = (templateParams, isFreeTemplate = true) => {
    const definedImage =
    templateParams.unsplashId ||
    templateParams.unsplashKeywords ||
    templateParams.imageUrl

  return isFreeTemplate
    ? {
      unsplashId: definedImage ? null : 'OeC1wIsKNpk',
      ...templateParams,
      watermark: 'Generated by ang-ec',
    }
    : templateParams
}